### PR TITLE
Dockerize the applications using Docker Compose

### PR DESCRIPTION
**Pull request by Artmorse**
## Services

- [x] : Write documentation on How to use it

### VSCode

- [x] : Access notebooks in VSCode
- [x] : Install [*ms-toolsai.jupyter* plugin](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) into VSCode
:arrow_right: I have created a Dockerfile to install the plugin

### QuestDB

- [x] : Configure the database name

### Grafana

- [x] : Configure the datasource
- [ ] : Configure the dashboard

### CODE REVIEW

**Review by BouarfaMahi — COMMENTED** [review]
use the default login access for both QuestDB and Grafana.

dbname=qdb
host=127.0.0.1
password=quest
port=8812
user=admin""")


Grafana
admin:admin

**Review by BouarfaMahi — COMMENTED** [review]
Install only supported version for code-server:  
jupyter  v2023.3.100
jupyter PowerToys  v0.0.6

Add to the README file : 
[How To Install and Use Docker on Ubuntu 22.04](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04)

[How To Install and Use Docker Compose on Ubuntu 22.04](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-ubuntu-22-04)

Before running docker-compose up, we need to download the necessary Docker files to local host.
Move the notebooks folder in the Docker folder and setup the notebooks folder as a shared directory in the Docker Compose file, so that any notebooks that we create or modify within the container should also be accessible from the local host.

The read/write permission on the shared folder should be set to allow both the container and the local host to access and modify the contents of the folder.   In the Docker Compose file, you can use the volumes section to specify the permissions for the mounted directory.

**Comment by Artmorse** [comment]
Regarding the links, you want to add to the docker/README.md file, please, can you create suggestions directly on the PR.

**Comment by Artmorse** [comment]
> Move the notebooks folder in the Docker folder

I'm not sure this is really necessary, for me we should let the `notebooks` folder at the root of the repository.

**Comment by BouarfaMahi** [comment]
> 



> > Move the notebooks folder in the Docker folder
> 
> I'm not sure this is really necessary, for me we should let the `notebooks` folder at the root of the repository.

Each microserver must have its own notebook folder on local host.

**Comment by Artmorse** [comment]
Extensions installed.

**Comment by Artmorse** [comment]
> Each microserver must have its own notebook folder on local host.

Yes, but it's already the case, WDYT?

**Comment by BouarfaMahi** [comment]
Features have not been completed, nor fully tested.

**Pull request closed without merging**
